version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: privateweb-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=qij2p3uo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=5ciuk1sy
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
  php:
    build: ./system/php
    container_name: privateweb-php
    ports:
      - '29114:80'
    volumes:
      - ./web:/var/www/html
    links:
      - mysql
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: privateweb-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 29115:80
    volumes:
      - /sessions
    links:
      - mysql
    restart: unless-stopped
volumes:
  db:
